### ISSUE TITLE
Required setters in API of Abstract Provider

### ISSUE THREAD

**Issue by stevenmaguire** [jobapis/jobs-common#12]
From JobBrander/jobs-authenticjobs/issues/2

> I am sensitive to the need for the API to remain as consistent as possible across all providers, however this will not be possible given the edge cases that we may need to support from time to time. For instance, in this particular case the setSort method for this provider will only respond successfully with provider specific entry, so the hope that a common API with setSort across all providers, while consistent, will not provider "hot swapping" of providers.
> 
> I think it would be a good idea to move this discussion to the common project and decide on a minimum set of "consistent" setters that each provider MUST implement, and provide no conflicts, then add them appropriate abstract methods to the AbstractProvider. In order to achieve this decision, I'd like to understand more clearly the use case you're encountering that highlights these differences.

**Comment by karllhughes** [comment]
@stevenmaguire I agree that not all setters will work with all providers. Didn't mean to imply any differently. I do think that certain setters should be expected in all providers though. The ones I would recommend are:
- setKeyword()
- setCity()
- setState()
- setPage()
- setCount()

So far the only place I'm using these setters is my demo app in [the activities class](https://github.com/karllhughes/jobs-api-client-demo/blob/master/app/Activities/JobsActivities.php).

My future implementation of our providers will be similar though. I'll need to set city, state, and keyword for any of the providers interchangeably. In my experience almost all the providers allow for these fields anyway, even if they do it in the form of a merged "location" field like the case we encountered this weekend.

**Comment by stevenmaguire** [comment]
I think `setKeyword`, `setPage`, and `setCount` are fair. They seem to line up nicely with any reasonably paginated service. The location ones, if required, will not always guarantee results. For example, the Elance API does not have a location filter available in its API.

https://www.elance.com/q/api2/methods/jobs/jobs

The Authentic Jobs API, much like the Indeed API, only expect a single filter for location. Both of those solutions now have a workaround to ensure city and state are merged "correctly" just before the request is made.

**Comment by karllhughes** [comment]
Damn, you elance!

What about this? https://github.com/JobBrander/jobs-govt/blob/master/src/Govt.php#L120

Basically the location (city/state) gets added to the keyword query

**Comment by stevenmaguire** [comment]
I think that is putting too much of the consuming application's opinion (Karl's opinion) into the project. My reaction to that is to remove the location setters from that project and provide documentation that encourages consumers of the project to include their location in the `setKeyword` method. If the API only provides keyword search, the project should only provide a keyword setter; it's more transparent. You, as a consumer are still free to "shove" anything you like into the filter.

This example from Govt jobs:

``` php
$jobs = $client->setKeyword('web designer in Chicago, IL')->getJobs();
```

would yield the same result as 

``` php
$jobs = $client->setKeyword('web designer')->setCity('Chicago')->setState('IL')->getJobs();
```

The short coming is on the Govt API, not the package, so the package doesn't need to pick up the slack.

**Comment by karllhughes** [comment]
That's fair. I definitely come at this from a bias as I've got a known objective for the projects in mind.

I'll make an issue in the govt jobs project to remove the get city/state methods and just include a line in the readme for this instead.

**Comment by karllhughes** [comment]
Found another issue. [The Muse's api](https://www.themuse.com/developers) doesn't even include a search or keyword input. You can query by:
- Location
- Job type
- Experience level
- Company
- Page

But no keyword.

Just something to throw out there.
