### ISSUE TITLE
Cataloguing methods in providers

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-common#13]
Because it's looking like each provider will have its own set up setter methods, I propose we begin cataloguing them in each provider.

Do you think the Readme is the most appropriate place for this @stevenmaguire? or should we include them as comments in the main class?

**Comment by stevenmaguire** [comment]
I already do this in the example code within the provider readme.  https://github.com/JobBrander/jobs-elance#usage

**Comment by karllhughes** [comment]
Good man. Always one step ahead of me :-)

I'll make a note to myself to do this in all the other providers and I'll close this issue.
