### ISSUE TITLE
New output formats

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-common#14]
Since we're moving away from standardizing the inputs as each API provider is so unique (damn snowflakes), I think it might be helpful to add new output formats. The first that comes to mind is CSV/Excel file output.

Just a thought, and no rush on this.

**Comment by stevenmaguire** [comment]
Can you describe the scenario for this?

**Comment by karllhughes** [comment]
It would make it easier for someone to pull down and save data to files if they didn't want/need a database.

What about adding eloquent models? We've already got the Job/Company objects as essentially DTOs, so that wouldn't be a stretch.

**Comment by stevenmaguire** [comment]
Ah, I see. I think it's not so much a jobs project then, as just as it is a Schema.org JobPosting formatter. I don't think this project should have the brunt of that responsibility. I think we should discuss this as a potential separate project that transforms the Schema.org standard objects into popular formats. Then we can evaluate the "weight" of that project to bundle it with this one as a dependency and expose it via API or if we update this project to suggest that one.

**Comment by karllhughes** [comment]
:+1:

**Comment by stevenmaguire** [comment]
Let's not close this until we actually have a game plan!

What formats are you interested in? So far CSV, Excel, Eloquent (I am not sure I fully understand this one), any others?

**Comment by karllhughes** [comment]
Okay, fine!

We could also do XML, although I don't know why people would still be using XML.

For eloquent, I was thinking of making some base models in a package that people who use eloquent (mostly Laravel/Lumen) could extend, and then making a transformer that would take the data returned from the API call and populate a model that the user could then save. This is my use case for importing jobs, so I'll be doing some work in this direction anyway.

**Comment by stevenmaguire** [comment]
I think XML is ok to add to the list and maybe take care of after the others. 

On the Eloquent side, I don't agree with creating a set of Eloquent models themselves and attempting to use them in downstream laravel/lumen applications. The models are tied directly to the applications database, which may have a different design. I do think the "formatting" project could offer a method or class that accepts an Eloquent model and attempts to populate it with data from our standardized objects. It would require some basic assumptions on how to map data and where to attempt to save or not. The use case would be something along the lines of: 

``` php
$mappings = ['city' => 'getCity'];
$hydratedModel = JobBrander\Transform\Eloquent::hydrateWithModel(
    Illuminate\Database\Eloquent\Model $model,
    JobBrander\Jobs\Client\Job $job,
   $mappings // optional mapping structure for Job to Model attributes
);
```

To provide models we would also need to provide migrations and assume that consumer would use them in their entirety.

**Comment by karllhughes** [comment]
@stevenmaguire I see what you mean with the migration problem. I guess it would sort of box customers into our model, which is probably a bit too tight to be helpful in most use cases.

I agree that a "formatter" or "transformer" class would be helpful. That's probably the bulk of the challenge that I'm facing in implementing our projects anyway.

**Comment by stevenmaguire** [comment]
What do you think about a new project `jobbrander/jobs-format` and a namespace of `JobBrander\Jobs\Format`?

Within the Format namespace we would offer the formats themselves in the form of a class for each? These would be the objects that were emitted.

`JobBrander\Jobs\Format\Csv.php`
`JobBrander\Jobs\Format\Xml.php`
`JobBrander\Jobs\Format\Eloquent.php`
`JobBrander\Jobs\Format\MySQL.php`
`JobBrander\Jobs\Format\MicrosoftExcel.php`
`JobBrander\Jobs\Format\GoogleSheet.php`

Then we can include a `Tools` namespace for generic operations that will no doubt be needed within each of the formatters.

`JobBrander\Jobs\Format\Tools`

And finally we would expose this functionality through a `Formatter` class that provides public methods to accept input and return the output?

``` php
<?php namespace JobBrander\Jobs\Format;

use Illuminate\Database\Eloquent\Model;
use JobBrander\Jobs\Client\Job;

class Formatter 
{
    /**
     * Hydrates eloquent model with given job.
     * 
     * @param  Model   $model
     * @param  Job     $job
     *
     * @return Model
     */
    public function toEloquent(Model $model, Job $job) {}

    /**
     * Creates xml object from given job.
     * 
     * @param  Job     $job
     *
     * @return JobBrander\Jobs\Format\Xml
     */
    public function toXml(Job $job) {}
}
```

**Comment by karllhughes** [comment]
@stevenmaguire I like it. Do you need me to set up the new repo or do you have the permissions to do it?

**Comment by stevenmaguire** [comment]
I see a new repo button, so I think I am good. Before we do that, I m on the fence about he vocabulary.

Should these objects be:
- Transformers
- Generators
- Formatters
- Something else?

**Comment by karllhughes** [comment]
I think "transformers" is most accurate. They aren't "generators" because the data is already there, but my creating actual models, I feel they're a little bigger than mere "formatters".

**Comment by stevenmaguire** [comment]
I've made [the new repository](https://github.com/JobBrander/jobs-transform) that references this issue. I will pull together the humble beginnings of the project there and we can continue discussion there as well.
