### ISSUE TITLE
convertCurrency() method doesn't work as expected for mixed inputs

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-common#2]
Careerbuilder returns salary data in a format like this: `$85k - $100k/year`

After the convertCurrency method tries to handle it, it turns into `85100`

A couple ways we could tackle this:
- Invalidate mixed inputs (ie: inputs with numbers and other character) in the convertCurrency method
- Make each provider responsible for converting mixed inputs to numbers or not passing them in if they're mixed

I like option 1 because it allows us to continue using the setMinimumSalary() method, but I'm open to discussion about this.

**Comment by stevenmaguire** [comment]
So in option 1, your example would have null as `baseSalary` because it would fail the `is_numeric` check in `convertCurrency`?

In general, I do like option 2 as it puts responsibility on the edge cases themselves to manage their own data exceptions.

**Comment by karllhughes** [comment]
Yeah, I think it's fine to put the responsibility on the provider as well. Currently it looks like Careerbuilder is the only one that does it like this, so it's just one case. I'll close this and open an issue in the Careerbuilder Provider to fix it there.
