### ISSUE TITLE
Figure out solution to testing query params in abstract class

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-common#23]
Testing the `$queryParams` variable in the v.2 of the abstract provider is tough as we're mocking the abstract class and then calling individual methods.

So far the only solution I've come up with is to write a concrete test class to implement it then call tests on the concrete implementation rather than on the abstract provider.

**Comment by stevenmaguire** [comment]
That's exactly what I'd recommend. Would you like me to help out there?

**Comment by karllhughes** [comment]
@stevenmaguire certainly. I've got a working MVP of the v2 in that branch, so feel free to make PRs on it to improve coverage/testability.

Thanks!

**Comment by karllhughes** [comment]
I did quite a bit of refactoring on my v2 stuff this week. I have decided to take a slightly different approach, but this issue still applies. My Provider and Query tests now both use a Concrete class to help with testing: https://github.com/jobapis/jobs-common/tree/v2-beta-query/tests/src
