### ISSUE TITLE
Add helper method to parse location into city and state from string

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-common#3]
Several of the providers I've been dealing with return city and state as a single string (eg: 'Chicago, IL'). In order to use the setCity() and setState() methods, I am just doing an explode call on them.

What do you think about adding a helper method to the job called 'setLocation()' that takes a string, parses the city and state, then calls the setCity and setState methods?

**Comment by stevenmaguire** [comment]
There is already a `setLocation` method that is a direct pass through to set a single string as the "Location". 

If I recall correctly, we had this discussion in the old repository and I believe we decided that it was the responsibility of the provider implementation to decide how that want to handle that as the `location` attribute is a string and `jobLocation` is the official address entity. 

I would be open to perhaps including a method that helped in the parsing of a single address string into location components and returning them to the provider, without adding any opinions about how the base provider will use those items. Something like:

``` php
/**
 * Parse location string into components.
 *
 * @param string $location
 * @return  array 
 **/
public static function parseLocation($location, $separator = ',')
{
    return array_map(function ($item) {
        return trim($item);
    }, explode($separator, $location));
}
```

``` php
$location = 'Chicago, IL 60610';
$locationItems = static::parseLocation($location);
print_r($locationItems);

Array
(
    [0] => 'Chicago'
    [1] => 'IL 60610'
)
```

The actual implementation would need some refinement to become more practical.

**Comment by karllhughes** [comment]
This is how I handle it for Dice and the other providers that need it:

```
$location = $this->parseLocation($payload['location']);

if (isset($location[0])) {
  $job->setCity($location[0]);
}
if (isset($location[1])) {
  $job->setState($location[1]);
}

public function parseLocation($location)
{
  return explode(', ', $location);
}
```

Where would be the best place to add helpers like this? The Job object or the AbstractProvider?

**Comment by stevenmaguire** [comment]
Yeah, thats the same as the Indeed provider. If we are going to include a helper method, I would recommend not hard coding the "glue", so the suggested method would be appropriate as it has a default comma "glue" and trims the parts. 

I would include it on the `AbstractProvider` as it is currently the provider's responsibility in the current use cases and it will not be responsible for any new opinions about how a job should handle the pieces.

The example you provided would look like the following after abstract provider implemented the above method:

``` php
$location = static::parseLocation($payload['location'], ', ');

if (isset($location[0])) {
  $job->setCity($location[0]);
}
if (isset($location[1])) {
  $job->setState($location[1]);
}
```

**Comment by karllhughes** [comment]
Okay, I can work on that this weekend. Thanks!

**Comment by stevenmaguire** [comment]
I merged. Looks good. If you run into any strange formatting issues, we may want to consider including the trim operation on the individual pieces that are returned.

**Comment by karllhughes** [comment]
@stevenmaguire agreed. So far they've all been the exact same, but I'll keep an eye out as I add more providers.
