### ISSUE TITLE
Uprade to guzzlehttp/guzzle 7.2 due to conflict with other packages

### ISSUE THREAD

**Issue by careerhub-source** [jobapis/jobs-common#30]
I get the error during installation, will you please upgrade it
Problem 1
    - jobapis/jobs-common[2.1.0, ..., 2.1.2] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires jobapis/jobs-common ^2.1 -> satisfiable by jobapis/jobs-common[2.1.0, 2.1.1, 2.1.2].

**Comment by chadidi** [comment]
@karllhughes can you publish the last commit, so it can be used on codebases that are using `jobapis/jobs-multi`. thanks 🙏
