### ISSUE TITLE
Using getParameters() Method

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-common#7]
What is the purpose of the getParameters() method? It seems that none of the providers use it (all return empty arrays), but it's declared in the abstract provider, so they all have to have the method.

Maybe this is deprecated?

**Comment by stevenmaguire** [comment]
This is the method by which providers can "inject" body data if they utilize the POST method the fetch job data. 

If we have built a fair number of providers and observed that most/all do not use it, then perhaps we could promote the method from being abstract to an implemented method in the abstract provider which would still allow providers who require that capability to override. I would recommend this over removal.

If you agree with this recommendation, I am happy to do the work.

**Comment by karllhughes** [comment]
I like the idea of making it implemented in the common project. Of the 8 providers we've done it hasn't been used, so it looks like it won't be commonly needed.

**Comment by stevenmaguire** [comment]
Cool. I'll take care of the jobs-common project. Then we can bump the release and I will take care of removing the method from the indeed project. Sound good?

**Comment by karllhughes** [comment]
Yep, sounds good
