### ISSUE TITLE
Versioning providers

### ISSUE THREAD

**Issue by karllhughes** [jobapis/jobs-common#8]
Just a question, how would you suggest we version providers? Should their major release number sync up with the major release of jobs-common? At what point should we move them to a 1.0 release?

Don't know if you have any strong opinions or know of any best practices @stevenmaguire but it would be great to get your thoughts.

**Comment by stevenmaguire** [comment]
Hey @karllhughes my immediate reaction to this question is that the individual providers do not need to mirror the version of the base package. In fact, it is probably better that we do not set that expectation as it will create extra work down stream whenever trivial updates are made to the common package or new releases do not impact specific providers. They should be free to work on their own versioning timeline.
